import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Database, PlusCircle, RefreshCw, } from 'lucide-react';
import { GithubIcon } from './GithubIcon';
export const Navbar = ({ repositories, selectedRepo, onSelectRepo, onOpenIngestModal, onResync, isResyncing, backendStatus, }) => {
    return (_jsxs("header", { className: "navbar", role: "banner", children: [_jsxs("div", { className: "nav-brand", children: [_jsx("div", { className: "nav-logo-icon", children: _jsx(Database, { size: 20 }) }), _jsxs("div", { children: [_jsxs("h1", { className: "nav-title", children: ["GitHub Analytics ", _jsx("span", { style: { color: 'var(--primary-light)', fontWeight: 400 }, children: "Lakehouse" })] }), _jsxs("div", { style: { display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.72rem', color: 'var(--text-dim)' }, children: [_jsx("span", { children: "Spark 3.5" }), _jsx("span", { children: "\u2022" }), _jsx("span", { children: "Iceberg 1.4" }), _jsx("span", { children: "\u2022" }), _jsx("span", { children: "MinIO S3" }), _jsx("span", { children: "\u2022" }), _jsx("span", { children: "Kafka" })] })] })] }), _jsxs("div", { className: "nav-actions", children: [_jsxs("div", { className: `badge ${backendStatus ? 'badge-emerald' : 'badge-rose'}`, title: backendStatus ? 'Connected to FastAPI & Lakehouse Storage' : 'FastAPI Offline', style: { padding: '6px 12px' }, children: [_jsx("span", { className: "pulse-dot", style: { backgroundColor: backendStatus ? '#10b981' : '#f43f5e' } }), _jsx("span", { children: backendStatus ? 'Lakehouse Online' : 'Engine Offline' })] }), repositories.length > 0 && (_jsxs("div", { className: "repo-select-wrapper", children: [_jsx(GithubIcon, { size: 15, style: { position: 'absolute', left: '10px', color: 'var(--text-muted)', pointerEvents: 'none' } }), _jsx("select", { id: "repo-selector", className: "repo-select", style: { paddingLeft: '32px' }, value: selectedRepo ? `${selectedRepo.owner}/${selectedRepo.name}` : '', onChange: (e) => {
                                    const found = repositories.find((r) => `${r.owner}/${r.name}` === e.target.value);
                                    if (found)
                                        onSelectRepo(found);
                                }, children: repositories.map((r) => (_jsxs("option", { value: `${r.owner}/${r.name}`, children: [r.owner, "/", r.name, " (", r.language || 'Code', ")"] }, r.id))) })] })), selectedRepo && (_jsxs("button", { id: "resync-btn", className: "btn btn-secondary btn-sm", onClick: onResync, disabled: isResyncing, title: "Incremental sync from GitHub", children: [_jsx(RefreshCw, { size: 14, style: { animation: isResyncing ? 'spin 1s linear infinite' : 'none' } }), _jsx("span", { children: isResyncing ? 'Syncing…' : 'Sync' })] })), _jsxs("button", { id: "open-ingest-modal-btn", className: "btn btn-primary btn-sm", onClick: onOpenIngestModal, children: [_jsx(PlusCircle, { size: 15 }), _jsx("span", { children: "Ingest Repository" })] })] }), _jsx("style", { children: `
        @keyframes spin {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
      ` })] }));
};
